import { build, context } from "esbuild";
import { mkdir, copyFile } from "fs/promises";
import path from "path";
import { builtinModules } from "module";

const mode = process.argv[2] ?? "watch";
const isProduction = mode === "production";
const isDevelopment = mode === "development";
const isWatch = mode === "watch";

const banner = `/* This file is generated by esbuild. Do not edit directly. */`;

const buildOptions = {
	entryPoints: ["src/main.ts"],
	bundle: true,
	format: "cjs",
	target: "es2024",
	outfile: "main.js",
	external: ["obsidian", "electron", ...builtinModules],
	treeShaking: true,
	minify: isProduction,
	sourcemap: isProduction ? false : "inline",
	banner: {
		js: banner,
	},
};

const testVaultPluginDir = path.resolve(
	"test-vault/.obsidian/plugins/quartz-syncer",
);

async function copyToTestVault() {
	await mkdir(testVaultPluginDir, { recursive: true });
	await copyFile("main.js", path.join(testVaultPluginDir, "main.js"));
	await copyFile(
		"manifest.json",
		path.join(testVaultPluginDir, "manifest.json"),
	);
	await copyFile(
		"styles.css",
		path.join(testVaultPluginDir, "styles.css"),
	);
}

async function runBuild() {
	if (isWatch) {
		const ctx = await context(buildOptions);
		await ctx.watch();
		await ctx.rebuild();
		await copyToTestVault();
		console.log("Watching for changes...");
		return;
	}

	await build(buildOptions);

	if (isDevelopment) {
		await copyToTestVault();
	}
}

runBuild().catch((error) => {
	console.error(error);
	process.exit(1);
});
